export const DEFAULT_LOGOUT_MODAL_ID = "cybexLogoutModal";
export const DEFAULT_SUPPORT_MODAL = "support_modal";
export const DEFAULT_ETO_CHECK_TOKEN = "DEFAULT_ETO_CHECK_TOKEN";
export const DEFAULT_HTLC_REDEEM_MODAL = "DEFAULT_HTLC_REDEEM_MODAL";
